### ISSUE TITLE
Feature Request Android : Selecting Friends based on Location and Contacts in mobile.

### ISSUE THREAD

**Issue by amitkrishnabits** [owntracks/talk#126]
- App should be able to locate Friends based on contacts saved in the phone.
- App should be able to identify Friends nearby based on phone number or a matching email address.
- App should have feature to lock a contact based on the choice of the user.

**Comment by growse** [comment]
Hi!

Interesting ideas around connecting the friends list with the phone contacts, although I'm not 100% sure exactly what you mean on some of them:

> App should be able to locate Friends based on contacts saved in the phone.

Can you describe a little bit more what you see this actually looking like?  Do you mean a deep link from the contacts app into that contact's location within the app (if it exists)?

> App should be able to identify Friends nearby based on phone number or a matching email address.

This is a little clearer - I assume that you mean that if the location coming from the friend contains some sort of identifier like a phone number, or an email address, it should be possible to match them to a contact and show the picture/name details that's in your contacts rather than what's on their published card?

> App should have feature to lock a contact based on the choice of the user.

Not sure what you mean by "lock" here.

**Comment by jpmens** [comment]
@t5ar it would be lovely if you could avoid the word "should". This is an open source project, and we do what is possible and what we consider useful to a larger community. We appreciate suggestions and as @growse has indicated, we  take lots of these seriously, but the word "should" hurts.

One of the definitions of _should_ is: must; ought (used to indicate duty, propriety, or expediency). If you don't mean it this way, I apologize for insinuating you may have done so.

I hope for your understanding.

**Comment by jpmens** [comment]
Closing as stale.
