### ISSUE TITLE
One-click setup with PikaPods

### ISSUE THREAD

**Issue by stevenroose** [owntracks/talk#160]
PikaPods is a paid service that allows setting up self-hosted softwares for personal use for a fee. For (almost?) all the softwares they support, they have revenue sharing agreements with the creators.

Since OwnTracks is known to be so meticulously hard to setup, this would be a great way to get more people to use it. Also it could mean some income for the creators.

I think if some of the OwnTracks folks get in touch with the PikaPods folks, they'd be happy to collaborate. Obviously they will need help creating the pod images etc but once that's done once, everyone could easily get a private OwnTracks in a few clicks!

You'd have your first customer in me.

I suggested it on the PikaPods feedback website here: https://feedback.pikapods.com/posts/255/add-owntracks

**Comment by jpmens** [comment]
We've created a [Quicksetup](https://owntracks.org/booklet/guide/quicksetup/) which  configures an MQTT server, our Recorder and Frontend with all bells and whistles as well as a configurable list of friends.

**Comment by grahamjpark** [comment]
Hi @jpmens, 

I just came across this thread because I also use Pikapods to host open source apps and am interested in using OwnTracks. I've added my vote to the request on [PikaPods's feedback site](https://feedback.pikapods.com/posts/255/add-owntracks).

Obviously it's on their side to onboard the app, but some reasons the it would also be in OwnTracks interest include:

1. Onboarding non-technical users
    - Expand audience of users to those who aren't technical enough to run their own server.
    - I've seen this happen with the [budgeting tool I use](https://actualbudget.org/).
    - Their prices are also pretty affordable compared to something like DigitalOcean from what I've seen
3. Funding for OwnTracks
    * Pikapods has revenue shares setup with several of the apps they support. I don't know the details
5. Exposure to FOSS fans
    * Getting the app included in the app catalog will help more people learn about it. I've discovered several apps by browsing the offerings
