### ISSUE TITLE
Removing devices from db

### ISSUE THREAD

**Issue by thecdnhermit** [owntracks/talk#161]
This is probably something I'm just not understanding one how Owntracks works, but I've been using Owntracks for a few years now and have switched up some device IDs. I need to know how to edit the database to remove nonexistent devices so my map isn't cluttered with current and old devices.

Can someone please help me out? Thanks!

**Comment by jpmens** [comment]
Assuming you mean remove IDs from the data store on the device, in the friends list you can swipe out one of the friends and it should disappear. Unless your mosquito broker will re-publish it in which case the device will obtain it again.

 In order to remove those you need to publish a retained, null payload on the appropriate topic to the MQTT broker.

**Comment by thecdnhermit** [comment]
So apparently I'm not as active here as I should be.

Swiping a friend listing from the list, or attempting to, doesn't seem to change anything. 

Can you give more details on the other option?

**Comment by jpmens** [comment]
Well, if you are using MQTT you would for each friend "delete" the retained message on broker-side. So, for a user `jane` with device `android` this would probably be

```console
$ mosquitto_pub -h <your-broker-IP> -u <username> -P <password> -t owntracks/jane/android -n -r
```

With `<username>` and `<password>` being the credentials for your broker.

**Comment by jpmens** [comment]
@thecdnhermit have we answered your question?
