### ISSUE TITLE
Enable fake location reporting

### ISSUE THREAD

**Issue by KenMacD** [owntracks/talk#182]
Hello, is there any support in the apps for manually configuring and reporting a custom/fake location? In balancing usefulness with privacy I'd like family members to be able to set a fixed location that would override the phone's actual location.

**Comment by jpmens** [comment]
Our apps don't have that capability, and I cannot imagine a reason to do so in the app. At best you can set the app to 'quiet mode' so that it no longer publishes its location.

What you could do is create/publish a location to the appropriate topic; there's nothing which checks whether such a location is legitimate.

**Comment by KenMacD** [comment]
Thank you. My thinking is that the app not publishing also gives away information so some way to 'freeze' the location would be better from a privacy perspective.
