### ISSUE TITLE
How to maximize location update frequency for Android

### ISSUE THREAD

**Issue by ToniTornado** [owntracks/talk#19]
Hi developers,

I want to achieve (near) real-time location tracking, i. e. location updates every 2-5 seconds if network availability allows that. The iOS version of Owntracks has the "move mode" - can this be configured with Android too? I read a lot and found in the booklet, that Android >= 6.0 somehow restricts heavy resource usage. I manually tweaked some options of my Android installation manually like locatorAccuracyBackground to 0 (successful) and locatorInterval and locatorDisplacement to 0 or very low values (no success).

Will an older Android version have any effect or be possible at all?

Will getting an iPhone and enabling move mode really solve my problem?

Can I force Android to just spoil resources? What limits did you find for location updates?

Right now I have my setup based on MQTT (seems better suited for real-time requirement) but the booklet encourages to use HTTP POST with Android -why?

Thank you for your help!

**Comment by binarybucks** [comment]
With accuracy and displacement set to 0 you will receive locations as fast as the device provides it. 
I got many updates on an old Moto E with Android 5.0 that way (draining battery like ther's no tomorrow). 

On Android > 6.0 nothing is guaranteed. Older versions **could** work better. 
I don't know if getting an iPhone will solve your problem because I don't know what your use case is. 
Owntracks 2.0 will throttle things even more and deliver batch updates every 30s in the best case with 1-2h when the app hasn't been opened in a long time (depends on Android version). 

You cannot really force it to spoil resources.
