### ISSUE TITLE
Monitoring network usage

### ISSUE THREAD

**Issue by przemas75** [owntracks/talk#47]
Hello,
Would love to see the enhancement to monitor data usage, similar like battery's one.
https://developer.android.com/reference/android/net/TrafficStats
So using wonderful mqttwarn, i could be alerted network usage is very high on my daughter's phone.
I mean traffic for all apps (summary), not only owntracks, which is low of course.

cheers

**Comment by jpmens** [comment]
@przemas75 thank you for the suggestion which we've looked at briefly. We've decided not to implement this at the moment because it's not relevant to our _location tracking_ task, and we want to cut short on features which appear to be cool but otherwise break at a later time when APIs etc. are changed.
