### ISSUE TITLE
Support or funding options?

### ISSUE THREAD

**Issue by AnandChowdhary** [owntracks/talk#75]
Thanking for building and maintaining OwnTracks! It's truly the best location tracking project out there, and I love how cross-platform it is.

I'm curious about how development currently happens (pro bono?) and whether it would be interesting to explore funding options, like Open Collective or GitHub Sponsors. I'm confident that frequent users would be happy to do small recurring donations to support the development. 😄

**Comment by jpmens** [comment]
Development happens pro bono, yes, and it's a lot of work. :)

Thanks for asking about funding. GitHub Sponsors doesn't yet seem to be available to all and su ndry, so that's out, and things like Patreon charge quite a bit, IIRC, for each contribution.

To be honest, it'd be nice to see an occasional tip in the jar, but we don't know how to go about this and whether it's actually worth the effort.

**Comment by Jotager** [comment]
any updates?
looking for a way to support as well
Paypal would be the best choice for me

**Comment by jpmens** [comment]
Thank you for asking, and we can finally report that we've set up [an OwnTracks team on Liberapay](https://liberapay.com/OwnTracks.org), where you can sponsor development or encouragement if you so desire. 

We appreciate your contributions, small and large. Thank you.

**Comment by mrose17** [comment]
just fyi: cf., https://github.com/owntracks/ios/issues/623#issuecomment-593146260

**Comment by jpmens** [comment]
So we have to install a specific Web browser, do I unstand that correctly?

**Comment by mrose17** [comment]
sorry for the length of this reply. 

it may be easier to just go to https://basicattentiontoken.org/ and watch the video at the top. here's something more concrete. the basic idea is this user attention is "denominated" by the BAT (basic attention token). if you opt-in, the browser keeps track of the sites you go to, the time you spend on pages, etc. none of this information leaves the browser. (a great deal of energy is spent to ensure that user behavior is correlated within only the browser and not at servers...)

# Publisher side
you don't need to run the brave browser (though i hope you do), but here's what you have to do:

1. in order for you (or any other github user, website, youtube channel, twitch channel, twitter user, vimeo channel, or reddit user), to claim the contributions: you need to go to https://publishers.basicattentiontoken.org/ and register an account. 

2. for something like github, you'll use oauth to verify that you are authorized to associate @jpmens with the publishers account. most publisher channels use oauth (a different mechanism is used for websites).

3. finally, you'll need an account at uphold.com in order to be able to do something with the tokens you are tipped. this is where the "real" world intrudes, in that things like KYC/AML begin to show up.

# User side
you have to be running the brave browser -- https://brave.com (Android, iOS, Linux, MacOS, and Windows)

1. you'll be asked to opt-in to brave rewards. if you are in a region without privacy-enhanced ads, you'll get a monthly grant of BAT that is contributed to the sites that you spend your time on.

2. you'll be asked to opt-in to brave ads. you'll get periodic notifications of privacy-enhanced ads and  get some BAT from the advertiser just for having the notification appear..

this is all opt-in. some folks never bother, and the browser will continue to block 3rd-party ads and a whole bunch of other things. if you do opt-in, the browser will put an icon in the URL bar letting you know about the site and Brave Rewards. it will also add a "Tip" icon where appropriate on github and reddit pages.

i hope this is helpful and not TMI... thanks!

**Comment by jpmens** [comment]
Thanks for taking the trouble to explain, but this is not for me: too much hassle, too many accounts; just not for me.

**Comment by mrose17** [comment]
understood... no worries! it works better for some, not others (like most things in life!)
