### ISSUE TITLE
Subscribing error (MQTT)

### ISSUE THREAD

**Issue by ketan0220** [owntracks/talk#94]
I tried sending a subscribe message to a subtopic, and it showed this (attached) error. Publishing works fine. I'm using Thingsboard. Messages sent from Thingsboard to devices (ios) are successful, however, the error mentioned popped out in the device.

I'm new in this matter so any kind of help is appreciated.

![Error](https://user-images.githubusercontent.com/65210184/81638775-ac751100-944c-11ea-9a62-80f77dfddf48.jpeg)

**Comment by ckrey** [comment]
We do not have experience with Thingsboard.

Please note that Thingsboard does not have a full MQTT implementation, but points out some limitations e.g. it does not support QoS 2. No idea what happens if you try to subscribe with QoS 2 https://thingsboard.io/docs/reference/mqtt-api/

Some MQTT implementations are incorrect. The MQTT library we use does strict checking according to the MQTT protocol specification. e.g. https://github.com/novastone-media/MQTT-Client-Framework/issues/369

Please check all your MQTT related settings, try subscribing with a different tool (e.g. `mosquitto_sub`) with the same settings, and report problem to Thingsboard

**Comment by ckrey** [comment]
@ketan0220 any news from your side?

**Comment by jpmens** [comment]
Closed for inactivity.
