### ISSUE TITLE
No pop-up shown when adding Integration in Hassio

### ISSUE THREAD

**Issue by RedSnowDonkey** [owntracks/talk#95]
Adding Owntracks integration in Hassio (on Rpi3) but clicking 'submit' just brings up a blank 'pop-up' box (and no URL details).  No combination of rebooting, deleting and re-adding the integration does anything different (i.e. still a blank pop-up, instead of http url details, etc.).

Any ideas why this is happening?

**Comment by RedSnowDonkey** [comment]
Sorry - was worried I wasn't opening this in the right place (so closed it, then couldn't find a 'better' place, so re-opened it again!).

**Comment by maceace** [comment]
Hello. 
A similar problem. I can't even get a window pop-up. I'm going to send it and nothing's going to happen. 
Managed to solve?

**Comment by jpmens** [comment]
This appears to be a "Hassio" problem, so please ask that project.

**Comment by maceace** [comment]
It will also owntrack share. 
Owntrack does it for security reasons. And he could tell us what we can't do to give us a OwnTrack webhook. Not a hero to close the topic.

**Comment by jpmens** [comment]
I closed the topic, because in my opinion the issue you have raised is not directly related to OwnTracks. For example: what is this WebHook you speak of? I don't think we have anything like this.

> It will also owntrack share. Owntrack does it for security reasons

I don't understand what you are trying to say. Can you please elaborate if you think it is an OwnTracks issue? If so, which of our apps are you using, on what devices, and with which versions?

I believe you can be better helped over at the Hassio project.

**Comment by maceace** [comment]
Yeah, okay.
After installing the OwnTrack add-on to HAss, a window will appear with the data that must be inserted into the application on the mobile device (URL (webhook)).
We are not receiving this window. We can't connect mobile devices to HAss.
I apologize if it is not within the competence of OwnTrack.
...
