### ISSUE TITLE
owntracksLog: Web scraping and sorting for OwnTracks data

### ISSUE THREAD

**Issue by ZacharyTalis** [owntracks/talk#96]
Hi folks! I made an executable tool, [owntracksLog](https://github.com/ZacharyTalis/owntracksLog), for my own location-tracking purposes. Sharing just in case someone else finds this useful!

When configured to run at startup on an internet-configured Windows computer, owntracksLog scrapes location data uploaded to Adafruit IO from an OwnTracks source. This data is then converted into two legible files, _owntracksLog.txt_ and _owntracksLog.csv_.

The repo contains a readme with comprehensive installation instructions.

**Comment by jpmens** [comment]
Do I understand correctly that you scrape location data other people erroneously/mistakenly publish in the clear? What is this useful for?

**Comment by ZacharyTalis** [comment]
> Do I understand correctly that you scrape location data other people erroneously/mistakenly publish in the clear? What is this useful for?

Nope! This is scraping your own data (using your private API key) off of Adafruit IO. You'd have to know someone else's API key in order to access their data using owntracksLog.

**Comment by jpmens** [comment]
Two comments if you don't mind:

1. I would try to access my own data via MQTT which they provide, IIRC
2. If you have the time and inclination I would do the parsing using a proper JSON parser; if we ever change the order of the JSON fields, I think your "parser" will fail.

I've marked this as a contribution so that other people might find it.

Good luck. :-)
